# Generated by Django 3.1.2 on 2020-11-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0005_auto_20201108_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='frameworks',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
