# Generated by Django 3.1.2 on 2020-11-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0006_tags_frameworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='frameworks',
        ),
    ]
