# Generated by Django 3.1.2 on 2020-11-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0007_remove_tags_frameworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='', max_length=50, verbose_name='User name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags',
            name='languages',
            field=models.CharField(max_length=50, verbose_name='Knowledge & skills'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tags.tags', verbose_name='Knowledge & skills'),
        ),
    ]
