# Generated by Django 3.1.2 on 2020-11-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0008_auto_20201108_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
    ]
